# docker-compose.yml

version: '3.4'


services:
  uniconfig-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ODL=odl:8181
    command: npm run dev
    ports:
      - 3000:3000
